package io.github.yuloong07star.luwi.channel

import android.view.KeyEvent

/**
 * The key names Android has, and what they mean
 *
 * A caller names a key instead of numbering one, and on a phone that difference matters: the
 * numbers are not memorable, and the half-remembered ones are the dangerous kind - keycode 5 is a
 * call, 26 is the power key, 27 is the camera. A name this table does not have is refused; a number
 * that is wrong is simply a different key, and the screen finds out afterwards
 *
 * The names are the platform's own, taken from `android/keycodes.h` (see
 * `tools/gen-keycodes.mjs`), so `BACK`, `KEYCODE_BACK` and `keycode_back` are one key and mean
 * exactly what the device means by it
 */
object KeyCodes {

    /**
     * The key a caller named, or null when Android has no key by that name
     *
     * A number is read as a keycode and checked against the same table, so a caller that remembers
     * `4` gets the key that really is 4, and one that remembers `45` gets nothing instead of
     * whatever 45 happens to be
     */
    fun resolve(text: String): Int? {
        val asked = text.trim()
        if (asked.isEmpty()) return null
        asked.toIntOrNull()?.let { return if (it in CODES) it else null }
        val bare = asked.uppercase()
            .removePrefix("AKEYCODE_")
            .removePrefix("KEYCODE_")
            .replace('-', '_')
            .replace(' ', '_')
        return BY_NAME[bare]
    }

    /** Whether this is a code the platform defines, which is the only kind worth injecting */
    fun known(code: Int): Boolean = code in CODES

    /**
     * What the platform calls a code, which is also the name this table files it under
     *
     * The prefix is dropped so an answer reads the way a caller would write it, and a code the
     * platform has no name for comes back as the number rather than as a guess
     */
    fun nameOf(code: Int): String {
        val said = KeyEvent.keyCodeToString(code).removePrefix("KEYCODE_")
        return if (said.startsWith("UNKNOWN")) code.toString() else said
    }

    /**
     * The keys that are about a whole screen rather than about what is running on one
     *
     * A screen of ours has no launcher and no system UI of its own, and these are the keys whose
     * entire meaning is "go somewhere else" or "stop showing this": measured on 192.168.1.103, a
     * HOME sent to a virtual screen left that display asleep with its last picture still being
     * handed out by `screencap`, which is a model reading a frozen frame and believing it. The
     * phone's own screen has all of that and is where these belong
     */
    val WHOLE_SCREEN: Set<Int> = setOf(
        KeyEvent.KEYCODE_HOME,
        KeyEvent.KEYCODE_POWER,
        KeyEvent.KEYCODE_SLEEP,
        KeyEvent.KEYCODE_SOFT_SLEEP,
    )

    /** The keys worth putting in front of a caller that named something Android does not have */
    val COMMON: List<String> = listOf(
        "BACK", "HOME", "APP_SWITCH", "MENU", "ENTER", "DEL", "FORWARD_DEL", "TAB", "ESCAPE",
        "SPACE", "DPAD_UP", "DPAD_DOWN", "DPAD_LEFT", "DPAD_RIGHT", "DPAD_CENTER",
        "VOLUME_UP", "VOLUME_DOWN", "VOLUME_MUTE", "POWER", "WAKEUP", "SLEEP", "NOTIFICATION",
        "SEARCH", "SETTINGS", "PAGE_UP", "PAGE_DOWN", "MOVE_HOME", "MOVE_END",
        "MEDIA_PLAY_PAUSE", "MEDIA_NEXT", "MEDIA_PREVIOUS", "CAMERA", "ASSIST",
    )

    // region generated by tools/gen-keycodes.mjs
    private const val TABLE = """
        UNKNOWN=0 SOFT_LEFT=1 SOFT_RIGHT=2 HOME=3 BACK=4 CALL=5 ENDCALL=6 0=7 1=8 2=9 3=10 4=11 5=12
        6=13 7=14 8=15 9=16 STAR=17 POUND=18 DPAD_UP=19 DPAD_DOWN=20 DPAD_LEFT=21 DPAD_RIGHT=22
        DPAD_CENTER=23 VOLUME_UP=24 VOLUME_DOWN=25 POWER=26 CAMERA=27 CLEAR=28 A=29 B=30 C=31 D=32 E=33
        F=34 G=35 H=36 I=37 J=38 K=39 L=40 M=41 N=42 O=43 P=44 Q=45 R=46 S=47 T=48 U=49 V=50 W=51 X=52
        Y=53 Z=54 COMMA=55 PERIOD=56 ALT_LEFT=57 ALT_RIGHT=58 SHIFT_LEFT=59 SHIFT_RIGHT=60 TAB=61
        SPACE=62 SYM=63 EXPLORER=64 ENVELOPE=65 ENTER=66 DEL=67 GRAVE=68 MINUS=69 EQUALS=70
        LEFT_BRACKET=71 RIGHT_BRACKET=72 BACKSLASH=73 SEMICOLON=74 APOSTROPHE=75 SLASH=76 AT=77 NUM=78
        HEADSETHOOK=79 FOCUS=80 PLUS=81 MENU=82 NOTIFICATION=83 SEARCH=84 MEDIA_PLAY_PAUSE=85
        MEDIA_STOP=86 MEDIA_NEXT=87 MEDIA_PREVIOUS=88 MEDIA_REWIND=89 MEDIA_FAST_FORWARD=90 MUTE=91
        PAGE_UP=92 PAGE_DOWN=93 PICTSYMBOLS=94 SWITCH_CHARSET=95 BUTTON_A=96 BUTTON_B=97 BUTTON_C=98
        BUTTON_X=99 BUTTON_Y=100 BUTTON_Z=101 BUTTON_L1=102 BUTTON_R1=103 BUTTON_L2=104 BUTTON_R2=105
        BUTTON_THUMBL=106 BUTTON_THUMBR=107 BUTTON_START=108 BUTTON_SELECT=109 BUTTON_MODE=110
        ESCAPE=111 FORWARD_DEL=112 CTRL_LEFT=113 CTRL_RIGHT=114 CAPS_LOCK=115 SCROLL_LOCK=116
        META_LEFT=117 META_RIGHT=118 FUNCTION=119 SYSRQ=120 BREAK=121 MOVE_HOME=122 MOVE_END=123
        INSERT=124 FORWARD=125 MEDIA_PLAY=126 MEDIA_PAUSE=127 MEDIA_CLOSE=128 MEDIA_EJECT=129
        MEDIA_RECORD=130 F1=131 F2=132 F3=133 F4=134 F5=135 F6=136 F7=137 F8=138 F9=139 F10=140 F11=141
        F12=142 NUM_LOCK=143 NUMPAD_0=144 NUMPAD_1=145 NUMPAD_2=146 NUMPAD_3=147 NUMPAD_4=148
        NUMPAD_5=149 NUMPAD_6=150 NUMPAD_7=151 NUMPAD_8=152 NUMPAD_9=153 NUMPAD_DIVIDE=154
        NUMPAD_MULTIPLY=155 NUMPAD_SUBTRACT=156 NUMPAD_ADD=157 NUMPAD_DOT=158 NUMPAD_COMMA=159
        NUMPAD_ENTER=160 NUMPAD_EQUALS=161 NUMPAD_LEFT_PAREN=162 NUMPAD_RIGHT_PAREN=163 VOLUME_MUTE=164
        INFO=165 CHANNEL_UP=166 CHANNEL_DOWN=167 ZOOM_IN=168 ZOOM_OUT=169 TV=170 WINDOW=171 GUIDE=172
        DVR=173 BOOKMARK=174 CAPTIONS=175 SETTINGS=176 TV_POWER=177 TV_INPUT=178 STB_POWER=179
        STB_INPUT=180 AVR_POWER=181 AVR_INPUT=182 PROG_RED=183 PROG_GREEN=184 PROG_YELLOW=185
        PROG_BLUE=186 APP_SWITCH=187 BUTTON_1=188 BUTTON_2=189 BUTTON_3=190 BUTTON_4=191 BUTTON_5=192
        BUTTON_6=193 BUTTON_7=194 BUTTON_8=195 BUTTON_9=196 BUTTON_10=197 BUTTON_11=198 BUTTON_12=199
        BUTTON_13=200 BUTTON_14=201 BUTTON_15=202 BUTTON_16=203 LANGUAGE_SWITCH=204 MANNER_MODE=205
        3D_MODE=206 CONTACTS=207 CALENDAR=208 MUSIC=209 CALCULATOR=210 ZENKAKU_HANKAKU=211 EISU=212
        MUHENKAN=213 HENKAN=214 KATAKANA_HIRAGANA=215 YEN=216 RO=217 KANA=218 ASSIST=219
        BRIGHTNESS_DOWN=220 BRIGHTNESS_UP=221 MEDIA_AUDIO_TRACK=222 SLEEP=223 WAKEUP=224 PAIRING=225
        MEDIA_TOP_MENU=226 11=227 12=228 LAST_CHANNEL=229 TV_DATA_SERVICE=230 VOICE_ASSIST=231
        TV_RADIO_SERVICE=232 TV_TELETEXT=233 TV_NUMBER_ENTRY=234 TV_TERRESTRIAL_ANALOG=235
        TV_TERRESTRIAL_DIGITAL=236 TV_SATELLITE=237 TV_SATELLITE_BS=238 TV_SATELLITE_CS=239
        TV_SATELLITE_SERVICE=240 TV_NETWORK=241 TV_ANTENNA_CABLE=242 TV_INPUT_HDMI_1=243
        TV_INPUT_HDMI_2=244 TV_INPUT_HDMI_3=245 TV_INPUT_HDMI_4=246 TV_INPUT_COMPOSITE_1=247
        TV_INPUT_COMPOSITE_2=248 TV_INPUT_COMPONENT_1=249 TV_INPUT_COMPONENT_2=250 TV_INPUT_VGA_1=251
        TV_AUDIO_DESCRIPTION=252 TV_AUDIO_DESCRIPTION_MIX_UP=253 TV_AUDIO_DESCRIPTION_MIX_DOWN=254
        TV_ZOOM_MODE=255 TV_CONTENTS_MENU=256 TV_MEDIA_CONTEXT_MENU=257 TV_TIMER_PROGRAMMING=258
        HELP=259 NAVIGATE_PREVIOUS=260 NAVIGATE_NEXT=261 NAVIGATE_IN=262 NAVIGATE_OUT=263
        STEM_PRIMARY=264 STEM_1=265 STEM_2=266 STEM_3=267 DPAD_UP_LEFT=268 DPAD_DOWN_LEFT=269
        DPAD_UP_RIGHT=270 DPAD_DOWN_RIGHT=271 MEDIA_SKIP_FORWARD=272 MEDIA_SKIP_BACKWARD=273
        MEDIA_STEP_FORWARD=274 MEDIA_STEP_BACKWARD=275 SOFT_SLEEP=276 CUT=277 COPY=278 PASTE=279
        SYSTEM_NAVIGATION_UP=280 SYSTEM_NAVIGATION_DOWN=281 SYSTEM_NAVIGATION_LEFT=282
        SYSTEM_NAVIGATION_RIGHT=283 ALL_APPS=284 REFRESH=285 THUMBS_UP=286 THUMBS_DOWN=287
        PROFILE_SWITCH=288 VIDEO_APP_1=289 VIDEO_APP_2=290 VIDEO_APP_3=291 VIDEO_APP_4=292
        VIDEO_APP_5=293 VIDEO_APP_6=294 VIDEO_APP_7=295 VIDEO_APP_8=296 FEATURED_APP_1=297
        FEATURED_APP_2=298 FEATURED_APP_3=299 FEATURED_APP_4=300 DEMO_APP_1=301 DEMO_APP_2=302
        DEMO_APP_3=303 DEMO_APP_4=304 KEYBOARD_BACKLIGHT_DOWN=305 KEYBOARD_BACKLIGHT_UP=306
        KEYBOARD_BACKLIGHT_TOGGLE=307 STYLUS_BUTTON_PRIMARY=308 STYLUS_BUTTON_SECONDARY=309
        STYLUS_BUTTON_TERTIARY=310 STYLUS_BUTTON_TAIL=311 RECENT_APPS=312 MACRO_1=313 MACRO_2=314
        MACRO_3=315 MACRO_4=316 EMOJI_PICKER=317 SCREENSHOT=318 DICTATE=319 NEW=320 CLOSE=321
        DO_NOT_DISTURB=322 PRINT=323 LOCK=324 FULLSCREEN=325 F13=326 F14=327 F15=328 F16=329 F17=330
        F18=331 F19=332 F20=333 F21=334 F22=335 F23=336 F24=337
    """
// endregion generated by tools/gen-keycodes.mjs

    /**
     * The table as name and code, read once
     *
     * The entries are wrapped across lines to stay readable beside the header they come from, so
     * what separates them is whitespace rather than a line break
     */
    private val BY_NAME: Map<String, Int> = TABLE.trimIndent().splitToSequence(' ', '\t', '\n', '\r')
        .mapNotNull { entry ->
            val split = entry.indexOf('=')
            val code = if (split <= 0) null else entry.substring(split + 1).toIntOrNull()
            if (code == null) null else entry.take(split) to code
        }
        .toMap()

    /** Every code the platform defines, for a caller that named a number instead */
    private val CODES: Set<Int> = BY_NAME.values.toSet()
}
