/**
 * Seed the agent preset on activation.
 *
 * Why this exists: the npm package carries the settings page, and every plugin
 * storefront installs a plugin with one command —
 * `dsh plugin --profile web add dsh-custom-mode`. Without this module that single
 * command produces a settings page whose preset does not exist on disk: the page opens
 * on "composition file not found", and the mode cannot even be picked for a new session.
 * A one-command install has to be a complete one.
 *
 * Why not a `postinstall` script: pnpm ≥ 10 blocks install scripts by default, and
 * marketplaces list them as a supply-chain risk. Seeding when the plugin activates is
 * both more reliable and less alarming.
 *
 * Three rules, in order of importance:
 *
 *  1. **Never overwrite.** `prompt.md` is the user's own text and `agent.cordis.yml` may
 *     have been generated by the settings page. Only missing files are written.
 *  2. **Never throw.** A read-only or otherwise unwritable `DSH_HOME` must not keep dsh
 *     from booting; the settings page reports the problem instead.
 *  3. **Idempotent.** A second activation writes nothing and changes nothing.
 */

import { existsSync, mkdirSync, readFileSync } from 'node:fs'
import { renderComposition } from './composition.mjs'
import { readPresetMeta, writePresetMeta } from './meta.mjs'
import { writeAtomic } from './atomic.mjs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/** The files a working preset needs. Order is the order they are written. */
export const PRESET_FILES = [
  'agent.cordis.yml',
  'preset.yml',
  'prompt.md',
  'prompt-reader.mjs',
  'prompt-tool.mjs',
]

/** Directory of the packaged copy: `preset/` beside this module (the package root is the repo root). */
export function packagedPresetDir() {
  return join(dirname(fileURLToPath(import.meta.url)), 'preset')
}

/** `error` as a readable string, without assuming it is an Error. */
function describe(error) {
  return String((error && error.message) || error)
}

/**
 * Fill in the preset files missing from `presetDir`, copying from `sourceDir`.
 *
 * @param {string} presetDir - the installed preset directory (`$DSH_HOME/.agent-presets/custom`).
 * @param {string} [sourceDir] - the packaged copy to copy from.
 * @returns {{created: string[], kept: string[], errors: string[]}} what happened, per file.
 */
/**
 * The starter composition for a newly seeded assistant, **derived from the composition the installed dsh line
 * actually ships**.
 *
 * **Why not copy the packaged file** (measured, and it was a real defect): the packaged `agent.cordis.yml` was
 * rendered from one dsh line, and the other line may not ship some of its rows. Concretely, the preview line's
 * standard composition enables `workflow-ptc` (`@deepseek-ai/dsh-workflow-ptc`), which the stable line
 * (`0.1.5-rc.2`) does not install at all — the platform's health check then marks the whole preset broken and
 * **silently drops the mode from every picker**, while the settings page keeps working (it never needs the
 * preset to be resolvable). Deriving the rows from what is installed makes that impossible by construction,
 * on any future line as well.
 *
 * @param {{mode?: string, assistantId?: string, modeName?: string}} [options]
 * @returns {string|null} rendered composition, or `null` when the installed composition cannot be read (the
 *   caller then keeps the packaged fallback file).
 */
export function starterComposition(options = {}) {
  const mode = typeof options.mode === 'string' && options.mode !== '' ? options.mode : 'standard'
  try {
    return renderComposition(mode, new Map(), {
      assistantId: typeof options.assistantId === 'string' ? options.assistantId : '',
      modeName: typeof options.modeName === 'string' ? options.modeName : '',
    })
  } catch (error) {
    console.error(
      'custom-mode: 无法从本机安装的出厂组成派生播种文件（' + describe(error) + '），改用包内模板。' +
        // 0.1.7 起这条是**预期**的：那条线不再有 `@deepseek-ai/dsh-agent-presets` 包，
        // 因而没有 presets/ 目录可派生 —— 出厂定义改成了 web-app bundle 里的声明行。
        // 模板能不能用不靠猜：宿主半边随后会用 `compositionInventory()` 的模块名集合
        // 逐行核对，装不了的行会指名报出来（见 index.mjs 的 doSync）。
        '若该 dsh 线已改用声明式 preset（0.1.7+），这是预期回退：那条线没有 presets/ 目录。' +
        '插件随后会核对模板的每一行能否在本机运行，装不了的行会被指名报出。',
    )
    return null
  }
}

/**
 * @param {string} presetDir - where the assistant lives.
 * @param {string} sourceDir - packaged template directory (tests inject their own).
 * @param {{composition?: string|null}} [options] - a rendered composition to write instead of copying
 *   `agent.cordis.yml`; see {@link starterComposition}.
 */
/**
 * 我们自己的**代码**模块（相对于"用户数据"）。
 *
 * 这两个文件是随助手目录一起分发的**代码**，不是用户内容：老版本创建的助手会一直留着旧副本，
 * 于是 1.0.x / 1.1.x 首装的用户即使把插件升到最新，会话内改写提示词的**审批闸门仍然是缺的** ——
 * 外部评审实测到了这一点（P1 安全）。所以它们在升级时**刷新**。
 * `prompt.md` / `preset.yml` / `agent.cordis.yml` 是用户数据（提示词、开关、名字），保持"只补不缺"。
 */
const REFRESHABLE_MODULES = ['prompt-reader.mjs', 'prompt-tool.mjs']

export function seedPreset(presetDir, sourceDir = packagedPresetDir(), options = {}) {
  const created = []
  const refreshed = []
  const kept = []
  const errors = []

  if (typeof presetDir !== 'string' || presetDir === '') {
    return { created, kept, errors: ['没有可用的 preset 目录路径'] }
  }
  if (!existsSync(sourceDir)) {
    return { created, kept, errors: [`包内预设目录不存在: ${sourceDir}`] }
  }
  try {
    mkdirSync(presetDir, { recursive: true })
  } catch (error) {
    // A read-only DSH_HOME lands here. Report it; do not attempt anything else.
    return { created, kept, errors: [`无法创建 ${presetDir}: ${describe(error)}`] }
  }

  for (const name of PRESET_FILES) {
    const target = join(presetDir, name)
    const source = join(sourceDir, name)
    if (existsSync(target)) {
      // 代码模块：内容与包内不一致就升级（用原子写，带 Windows 重试）。
      if (REFRESHABLE_MODULES.includes(name) && existsSync(source)) {
        try {
          const shipped = readFileSync(source, 'utf8')
          if (readFileSync(target, 'utf8') !== shipped) {
            writeAtomic(target, shipped)
            refreshed.push(name)
            continue
          }
        } catch (error) {
          errors.push(`刷新 ${name} 失败: ${describe(error)}`)
          continue
        }
      }
      kept.push(name)
      continue
    }
    // 组成文件优先用"按本机那条线派生"的内容；只有派生失败（null）时才退回包内模板。
    if (name === 'agent.cordis.yml' && typeof options.composition === 'string' && options.composition !== '') {
      try {
        writeAtomic(target, options.composition)
        created.push(name)
        continue
      } catch (error) {
        errors.push(`写入 ${name} 失败: ${describe(error)}`)
        continue
      }
    }
    if (!existsSync(source)) {
      errors.push(`包内缺少 ${name}`)
      continue
    }
    try {
      // 原子写（内部带 Windows 重试）：原先裸 copyFileSync 在两个实例共抢一个 DSH_HOME 首启时会 EBUSY。
      writeAtomic(target, readFileSync(source, 'utf8'))
      created.push(name)
    } catch (error) {
      errors.push(`写入 ${name} 失败: ${describe(error)}`)
    }
  }
  return { created, refreshed, kept, errors }
}

/**
 * We shipped a **bilingual** description (`中文 / English`) for three years' worth of installs.
 *
 * It was a workaround with a real cause: the description is **product data** in `preset.yml`, and the shell
 * renders it in whatever language the UI happens to be in — it localises its own shipped presets, but it
 * cannot localise ours. A bilingual line then read as one language inside the other, which is exactly the
 * complaint that came back ("英文是英文中文是中文，不要混杂"): in the mode picker the entry showed
 * `完整编码能力… / Full coding ability…` as a single run-on string, and it was long enough to make that
 * card taller than the shipped ones next to it.
 *
 * So the template no longer ships a description at all: an absent description is a state the shell already
 * supports (it prints its own "no description" placeholder), it cannot be wrong in either language, and the
 * field stays user-editable on the settings page.
 *
 * This migrates installs that still carry **one of our own shipped strings verbatim**. Anything else — a
 * description the user typed, however similar — is left alone: that is the whole contract of this file.
 */
export const SHIPPED_DESCRIPTIONS = [
  "在设置页编辑本模式的系统提示词 / Edit this mode's system prompt in Settings.",
  '完整编码能力，系统提示词来自 prompt.md，可在设置页随时修改、下一步即生效。 / Full coding ability; the system prompt lives in prompt.md and can be edited in the settings page — it takes effect on the next step.',
]

/**
 * Blank the description **only** when it is one of {@link SHIPPED_DESCRIPTIONS}.
 *
 * @param {string} presetDir - the installed preset directory.
 * @returns {{migrated: boolean, reason?: string}} what happened.
 */
export function dropShippedDescription(presetDir) {
  const file = join(presetDir, 'preset.yml')
  if (!existsSync(file)) return { migrated: false, reason: 'no preset.yml' }
  let meta
  try {
    meta = readPresetMeta(presetDir)
  } catch (error) {
    return { migrated: false, reason: describe(error) }
  }
  const current = typeof meta.description === 'string' ? meta.description.trim() : ''
  if (current === '' || SHIPPED_DESCRIPTIONS.includes(current) === false) return { migrated: false, reason: 'user text' }
  const written = writePresetMeta(typeof meta.name === 'string' && meta.name.trim() !== '' ? meta.name : '自定义模式', '', presetDir)
  return written.ok === true ? { migrated: true } : { migrated: false, reason: String(written.code ?? 'writeFailed') }
}

/**
 * Seed and report, in the form the host half logs.
 *
 * Silent when the preset was already complete — the common case after the first
 * activation, and after `./install.sh`, which copies the same files itself.
 *
 * @param {string} presetDir - destination preset directory.
 * @param {(message: string) => void} [log] - error sink (defaults to console.error).
 * @param {(message: string) => void} [info] - info sink (defaults to console.log).
 * @param {string} [sourceDir] - packaged template to copy from (defaults to `preset/` beside this module).
 * @returns {{created: string[], kept: string[], errors: string[]}}
 */
export function seedPresetWithLog(presetDir, log = console.error, info = console.log, sourceDir = packagedPresetDir(), options = {}) {
  let result
  try {
    result = seedPreset(presetDir, sourceDir, options)
  } catch (error) {
    // seedPreset is written not to throw; this is a last-resort guard so that a bug here
    // can never stop the host from booting.
    log(`custom-mode: 播种 preset 时出现意外错误（已忽略）: ${describe(error)}`)
    return { created: [], kept: [], errors: [describe(error)] }
  }
  if (result.refreshed !== undefined && result.refreshed.length > 0) {
    info(`custom-mode: 已刷新 ${presetDir} 里的代码模块（${result.refreshed.join(', ')}）`)
  }
  if (result.created.length > 0) {
    info(`custom-mode: 已播种 preset 到 ${presetDir}（新建 ${result.created.length} 个文件: ${result.created.join(', ')}）`)
  }
  // 只订正**我们自己写进去的**那条描述（见 dropShippedDescription）。
  try {
    if (dropShippedDescription(presetDir).migrated === true) {
      info(`custom-mode: 已清空描述 —— 它还是我们早年播种的那条中英拼接，壳无法按界面语言本地化产品数据`)
    }
  } catch (error) {
    log(`custom-mode: 描述迁移失败（已忽略）: ${describe(error)}`)
  }
  for (const error of result.errors) {
    log(`custom-mode: preset 播种未完成 —— ${error}`)
  }
  if (result.errors.length > 0) {
    log(`custom-mode: 设置页仍可打开，但组成文件可能缺失，见 docs/TROUBLESHOOTING.zh.md`)
  }
  return result
}
